# Generated by Django 4.1.6 on 2023-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0003_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50)),
                ('HotelName', models.CharField(blank=True, max_length=50)),
                ('Address', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
