# Generated by Django 4.1.6 on 2023-02-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0004_vendorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
