# Generated by Django 4.1.6 on 2023-02-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0005_emailnotificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='Message',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='subject',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
