# Generated by Django 4.1.6 on 2023-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0006_alter_emailnotificationmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='Message',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='recipient_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
