# Generated by Django 4.1.6 on 2023-02-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0007_alter_emailnotificationmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotificationmodel',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
