# Generated by Django 4.1.6 on 2023-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0008_alter_emailnotificationmodel_recipient_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotificationmodel',
            old_name='Message',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='emailnotificationmodel',
            name='recipient_email',
        ),
        migrations.RemoveField(
            model_name='emailnotificationmodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailnotificationmodel',
            name='message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
