# Generated by Django 4.1.6 on 2023-02-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0011_bus_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
