# Generated by Django 4.1.6 on 2023-02-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0012_delete_bus_delete_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='Hotel_Price',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
