# Generated by Django 4.1.6 on 2023-02-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0015_alter_vendorrequest_hotel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrequest',
            name='Hotel_Price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
