# Generated by Django 4.1.6 on 2023-02-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0016_alter_vendorrequest_hotel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrequest',
            name='Hotel_Price',
        ),
    ]
