# Generated by Django 4.1.6 on 2023-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0017_remove_vendorrequest_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorrequest',
            name='Hotel_Price',
            field=models.IntegerField(default=0),
        ),
    ]
