# Generated by Django 4.1.6 on 2023-03-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0018_vendorrequest_hotel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEditModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
            ],
        ),
    ]
