# Generated by Django 4.1.6 on 2023-03-02 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0019_profileeditmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileeditmodel',
            name='email',
        ),
    ]
