# Generated by Django 4.1.6 on 2023-03-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0020_remove_profileeditmodel_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileEditModel',
        ),
    ]
