# Generated by Django 4.1.6 on 2023-03-04 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0022_vendorrequest_hotel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoomType',
            fields=[
                ('Room_ID', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Room_Token', models.CharField(blank=True, max_length=200)),
                ('Room_Price', models.IntegerField(default=0)),
                ('Room_Type', models.CharField(default=True, max_length=50)),
                ('Refundadle_Option', models.CharField(default=True, max_length=50)),
                ('Hotel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegster_app.vendorrequest')),
            ],
        ),
    ]
