# Generated by Django 4.1.6 on 2023-03-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0024_remove_hotelroomtype_room_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room_ID',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='hotelroomtype',
            name='Room_Token',
        ),
    ]
