# Generated by Django 4.1.6 on 2023-03-04 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0025_remove_booking_room_id_remove_booking_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Room_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.hotelroomtype'),
        ),
    ]
