# Generated by Django 4.1.6 on 2023-03-04 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0026_booking_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room_ID',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
