# Generated by Django 4.1.6 on 2023-03-04 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0027_remove_booking_room_id_booking_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Hotel_ID',
        ),
        migrations.AddField(
            model_name='booking',
            name='Room_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.hotelroomtype'),
        ),
    ]
