# Generated by Django 4.1.6 on 2023-03-04 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0028_remove_booking_hotel_id_booking_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Room_ID',
        ),
        migrations.AddField(
            model_name='booking',
            name='Hotel_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.vendorrequest'),
        ),
        migrations.AddField(
            model_name='hotelroomtype',
            name='Room_Token',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
