# Generated by Django 4.1.6 on 2023-03-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0030_remove_booking_hotel_id_booking_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomtype',
            name='Bed_Type',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
