# Generated by Django 4.1.6 on 2023-03-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0031_hotelroomtype_bed_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelroomtype',
            old_name='Refundadle_Option',
            new_name='Refundable_Option',
        ),
    ]
