# Generated by Django 4.1.6 on 2023-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0033_bus_busbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='Busname',
        ),
        migrations.RenameField(
            model_name='busbooking',
            old_name='name',
            new_name='Passenger_name',
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
