# Generated by Django 4.1.6 on 2023-03-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0034_rename_name_bus_busname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
