# Generated by Django 4.1.6 on 2023-03-06 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0035_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Type', models.CharField(blank=True, max_length=100)),
                ('Bed_Type', models.CharField(default=True, max_length=50)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Refundable_Option', models.CharField(default=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('Hotel_email', models.CharField(blank=True, max_length=50)),
                ('HotelName', models.CharField(blank=True, max_length=50)),
                ('Hotel_Location', models.CharField(blank=True, max_length=50)),
                ('Payment', models.CharField(choices=[('khalti', 'KHALTI'), ('cash_on_delivery', 'CASH_ON_DELIVERY')], default='cash_on_delivery', max_length=20)),
                ('Order_Status', models.CharField(choices=[('Pending', 'PENDING'), ('Booking_completed', 'BOOKING_COMPLETED'), ('Booking_Canceled', 'BOOKING_CANCELED')], default='Pending', max_length=20)),
                ('Payment_Completed', models.BooleanField(default=False)),
                ('Hotel_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wegster_app.vendorrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
