# Generated by Django 4.1.6 on 2023-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0036_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='Check_out_Date',
            field=models.DateField(blank=True,  null=True),
        ),
        migrations.AddField(
            model_name='hotelbooking',
            name='check_in_Date',
            field=models.DateField(blank=True,  null=True),
        ),
    ]
