# Generated by Django 4.1.6 on 2023-03-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0037_hotelbooking_check_out_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='seats',
            new_name='no_of_seats',
        ),
        migrations.RenameField(
            model_name='busbooking',
            old_name='seat_number',
            new_name='numberofseat',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='Check_out_Date',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='check_in_Date',
        ),
        migrations.AddField(
            model_name='bus',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='dest',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='source',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='dest',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='source',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=2),
        ),
        migrations.AddField(
            model_name='busbooking',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='Payment',
            field=models.CharField(choices=[('khalti', 'KHALTI'), ('cash_Indoor', 'CASH_ON_DELIVERY')], default='cash_Indoor', max_length=20),
        ),
    ]
