# Generated by Django 4.1.6 on 2023-03-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0038_rename_seats_bus_no_of_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='busbooking',
            name='time',
        ),
    ]
