# Generated by Django 4.1.6 on 2023-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0040_alter_busbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='Payment',
            field=models.CharField(choices=[('khalti', 'KHALTI'), ('cash_Indoor', 'CASH_INDOOR')], default='cash_Indoor', max_length=20),
        ),
    ]
