# Generated by Django 4.1.6 on 2023-03-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0042_busbooking_date_busbooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
