# Generated by Django 4.1.6 on 2023-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0044_alter_busbooking_date_alter_busbooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='id',
        ),
        migrations.AddField(
            model_name='bus',
            name='Bus_ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='busbooking',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('P', 'Pending')], default='P', max_length=2),
        ),
    ]
