# Generated by Django 4.1.6 on 2023-03-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0045_remove_bus_id_bus_bus_id_alter_busbooking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='bus',
            new_name='Bus_ID',
        ),
    ]
