# Generated by Django 4.1.6 on 2023-03-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0046_rename_bus_busbooking_bus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='status',
            field=models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled'), ('P', 'Pending')], default='pending', max_length=2),
        ),
    ]
