# Generated by Django 4.1.6 on 2023-03-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0049_alter_busbooking_seat_id_alter_seat_bus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='dest',
            field=models.CharField(default=True, max_length=30, null=True),
        ),
    ]
