# Generated by Django 4.1.6 on 2023-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0050_busbooking_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='totalSeats',
            field=models.IntegerField(default=0),
        ),
    ]
