# Generated by Django 4.1.6 on 2023-03-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0051_bus_totalseats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='Bus_ID',
        ),
        migrations.DeleteModel(
            name='Busbooking',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
