# Generated by Django 4.1.6 on 2023-03-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0052_remove_seat_bus_id_delete_busbooking_delete_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Bus_ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
