# Generated by Django 4.1.6 on 2023-03-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0053_alter_bus_bus_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('Seat_ID', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('Seat_number', models.CharField(max_length=10)),
                ('available', models.BooleanField(default=True)),
                ('Bus_ID', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.bus')),
            ],
        ),
    ]
