# Generated by Django 4.1.6 on 2023-03-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0054_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='Passenger_Name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
