# Generated by Django 4.1.6 on 2023-03-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0055_seat_passenger_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='Passenger_Name',
        ),
    ]
