# Generated by Django 4.1.6 on 2023-03-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0057_busbooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busbooking',
            old_name='Passenger_Name',
            new_name='name',
        ),
    ]
