# Generated by Django 4.1.6 on 2023-03-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0060_alter_seat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='Seat_ID',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.seat'),
        ),
    ]
