# Generated by Django 4.1.6 on 2023-03-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0061_busbooking_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomtype',
            name='Room_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
