# Generated by Django 4.1.6 on 2023-03-23 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0066_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Hotel_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wegster_app.vendorrequest'),
        ),
    ]
