# Generated by Django 4.1.6 on 2023-03-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0069_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='text',
        ),
        migrations.AddField(
            model_name='review',
            name='Customet_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='Hotel_Name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='Review',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='review',
            name='Rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
