# Generated by Django 4.1.6 on 2023-03-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0070_remove_review_rating_remove_review_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Customet_Name',
            new_name='Customer_Name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Hotel_Name',
            new_name='Hotelname',
        ),
    ]
