# Generated by Django 4.1.6 on 2023-05-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0071_rename_customet_name_review_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbooking',
            name='Seat_ID',
        ),
        migrations.AddField(
            model_name='busbooking',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
