# Generated by Django 4.1.6 on 2023-05-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0074_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='Bus_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='Seat_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendorrequest',
            name='Hotel_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
