# Generated by Django 4.1.6 on 2023-05-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0075_alter_bus_bus_id_alter_seat_seat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorrequest',
            name='Hotel_ID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
