# Generated by Django 4.1.6 on 2023-05-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0076_alter_vendorrequest_hotel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbooking',
            name='Payment',
            field=models.CharField(choices=[('khalti', 'KHALTI'), ('cash_on_Arrival', 'CASH_ON_ARRIVAL')], default='cash_on_Arrival', max_length=20),
        ),
    ]
