# Generated by Django 4.1.6 on 2023-05-25 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0077_alter_busbooking_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelbooking',
            name='Payment',
            field=models.CharField(choices=[('khalti', 'KHALTI'), ('cash_on_door', 'CASH_ON_DOOR')], default='cash_on_door', max_length=20),
        ),
    ]
