# Generated by Django 4.1.6 on 2023-05-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wegster_app', '0078_alter_hotelbooking_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorrequest',
            name='Hotel_Price',
        ),
    ]
